eureka:
  client:
    service-url:
      #将eureka server1注册到eureka server2中去8762，两台服务端互相注册8761<---->8762
      defaultZone: http://localhost:8762/eureka/
    #eureka 高可用时，register-with-eureka: true
    register-with-eureka: true

  #开发环境可以false，但是生产环境尽量true。
  #关于eureka 环境的自我保护，开发环境dev时可以关闭为false，但是生产环境prod时要打卡为true。
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka

#项目的端口号
#server:
#  port: 8761
management:
  context-path: /
